---
title: "Daily Temperature Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(httr)

```

```{r, cache = TRUE}
# This code is borrowed and modified from the code in the Data API tutorial in
# the primer.tutorials package. It is quite hacky! Surely, there is a way to ask
# for two stations at once rather than making two separate calls to the API.
# Also, this download currently gets data for each hour during the day. I don't
# really need that much data. Just getting the daily high would be good enough.

meso_url <- "https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py/"

denver_response <- GET(url = meso_url,
    query = list(station = "DEN",
                 data = "tmpf",
                 year1 = "2017",
                 month1 = "01",
                 day1 = "01",
                 year2 = "2021",
                 month2 = "12",
                 day2 = "31",
                 tz = "America/Denver"))

denver_p <- denver_response %>%
  content() %>% 
  read_csv(na = "M") %>% 
  separate(col = valid,
           into = c("date", NA),
           sep = " ") %>% 
  drop_na()

sf_response <- GET(url = meso_url,
    query = list(station = "SFO",
                 data = "tmpf",
                 year1 = "2017",
                 month1 = "01",
                 day1 = "01",
                 year2 = "2021",
                 month2 = "12",
                 day2 = "31",
                 tz = "America/Denver"))


sf_p <- sf_response %>%
  content() %>% 
  read_csv(na = "M") %>% 
  separate(col = valid,
           into = c("date", NA),
           sep = " ") %>% 
  drop_na()

# Quick review suggests that the data is OK. Certainly, it has the main feature
# we want: temperature in Denver is about 3x more variable than in SF. But why
# are the about 5% fewer observations for SFO then for DEN? Ought to look at
# this more closely.

x <- bind_rows(denver_p, sf_p)

write_csv(x, file = "data/temperatures.csv")
 
```

